title: Tech Blog
description: >-
  Make your ideas  <br>
  come true.
url: "https://github.com/"
github: hayleyshim
email: yhshim17@gmail.com
google_analytics: G-1KSR3STMG1

exclude: [README.md, Gemfile, Gemfile.lock]

comments:
  enabled: true
  repo: hayleyshim 
  issue-term: pathname
  theme: github-light

collections:
  pages:
    output: true
  projects:
    output: true
  tags:
    output: true

defaults:
  - scope:
      type: pages
    values:
      layout: default
  - scope:
      type: posts
    values:
      layout: post
      permalink: /blog/:title
  - scope:
      type: projects
    values:
      layout: project
      permalink: /projects/:title
  - scope:
      type: tags
    values:
      layout: tag
      permalink: /tags/:title
